spring.application.name=childsupport

spring.datasource.url=jdbc:postgresql://localhost:5432/childsupport
spring.datasource.username=postgres
spring.datasource.password=Fignomen8098!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=gishath-suns-avatar-is-the-best-card-ever-yes-it-sure-is
jwt.expiration=86400000

server.port=8080